trigger:
  branches:
    include:
      - master
      - release/beta/*
      - release/stable/*
      - feature/*

pr: 
  branches:
    include:
      - master
      - release/beta/*
      - release/stable/*
      - feature/*
      
  paths:
    include:
    - '/'
    exclude:
    - .dependabot/
    - .github/
    - doc/*
    - .all-contributorsrc

resources:
  containers:
  - container: nv-bionic-wasm
    image: unoplatform/wasm-build:3.0

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  windows2019HostedVMImage: 'windows-2019'
  windows2022HostedVMImage: 'windows-2022'
  windowsScaledPool: 'Windows2022-20211130'
  linuxVMImage: 'ubuntu-latest'
  macOSVMImage: 'macOS-11'
  macOSVMImage_UITests: 'macOS-10.15'
  xCodeRoot: '/Applications/Xcode_13.1.app'
  XamarinSDKVersion: 6_12_7
  xCodeRoot_iOS_UITests: '/Applications/Xcode_11.5.app'
  XamarinSDKVersion_iOS_UITests: 6_10_0

jobs:
- template: build/ci/.azure-devops-commitsar.yml
  parameters:
    vmImage: '$(linuxVMImage)'

- template: build/ci/.azure-devops-pipeline-validations.yml
  parameters:
    vmImage: '$(linuxVMImage)'

- template: build/ci/.azure-devops-docs.yml
  parameters:
    vmImage: '$(windows2022HostedVMImage)'
